# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "A command-line tool for Bitbucket Cloud"
  homepage "https://github.com/PhilipKram/Bitbucket-CLI"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PhilipKram/Bitbucket-CLI/releases/download/v0.0.5/bb_0.0.5_darwin_amd64.tar.gz"
      sha256 "d539850e0e94d6f9b8971a4c028cec68b6e3f11a3205e196a00e19679ce08f8a"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PhilipKram/Bitbucket-CLI/releases/download/v0.0.5/bb_0.0.5_darwin_arm64.tar.gz"
      sha256 "08257a0791000639eb0b0494bdb72a4b7e9536e69505dd69d3864bd09275e47e"

      def install
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Bitbucket-CLI/releases/download/v0.0.5/bb_0.0.5_linux_amd64.tar.gz"
      sha256 "6ebdc43434c03fe1dee732eb9d2f2ee1eecccd6f84a387360b8e23b608ad242f"
      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Bitbucket-CLI/releases/download/v0.0.5/bb_0.0.5_linux_arm64.tar.gz"
      sha256 "5b115e6ea381519515e568a3a7cb45fbab973e128b47ab5b2400d3ca90a42e82"
      def install
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb", "--version"
  end
end
