# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "A command-line tool for Bitbucket Cloud"
  homepage "https://github.com/PhilipKram/Bitbucket-CLI"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PhilipKram/Bitbucket-CLI/releases/download/v0.4.0/bb_0.4.0_darwin_amd64.tar.gz"
      sha256 "d554a09533184f8aae8c1b71baf295a6f4f5552d258bc619a134073bb8125a58"

      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PhilipKram/Bitbucket-CLI/releases/download/v0.4.0/bb_0.4.0_darwin_arm64.tar.gz"
      sha256 "b8440c35e1a65e6593074af6153dd31347066794f05ea6cec9691989e83be15a"

      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Bitbucket-CLI/releases/download/v0.4.0/bb_0.4.0_linux_amd64.tar.gz"
      sha256 "70baf2bb13575cb84a4283e5a383c04e9c397235dcbfc0a2f752c394407f05a6"
      define_method(:install) do
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Bitbucket-CLI/releases/download/v0.4.0/bb_0.4.0_linux_arm64.tar.gz"
      sha256 "889740094e87e3afc2b48bf45860b2990972fbb4cd4941ae06e1f9facaeb495c"
      define_method(:install) do
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb", "--version"
  end
end
