# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glab < Formula
  desc "A CLI tool for GitLab, similar to GitHub CLI (gh)"
  homepage "https://philipkram.github.io/Gitlab-CLI/"
  version "0.2.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.2.0/glab_0.2.0_darwin_amd64.tar.gz"
      sha256 "6fde7549938e8057eed5ee60713608b021b31bf05af727160b3279f581e4ef41"

      define_method(:install) do
        bin.install "glab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.2.0/glab_0.2.0_darwin_arm64.tar.gz"
      sha256 "495a9fe3df60f1121c758f825940f3e490074e132e60d888e85b09e2ca7fa4c4"

      define_method(:install) do
        bin.install "glab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.2.0/glab_0.2.0_linux_amd64.tar.gz"
      sha256 "ee82b15ba2c1d90ba20cceda8042ac7896137d060a043a6040865ef0a1179853"
      define_method(:install) do
        bin.install "glab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.2.0/glab_0.2.0_linux_arm64.tar.gz"
      sha256 "cec76e1c4b271454ffffcbc1b4525f71de787793fad372ba9631fb1447494324"
      define_method(:install) do
        bin.install "glab"
      end
    end
  end

  test do
    assert_match "glab version", shell_output("#{bin}/glab --version")
  end
end
