# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glab < Formula
  desc "A CLI tool for GitLab, similar to GitHub CLI (gh)"
  homepage "https://philipkram.github.io/Gitlab-CLI/"
  version "0.12"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.12/glab_0.12_darwin_amd64.tar.gz"
      sha256 "c40bd1d4d6636292aa90b99ae828136ce4c19fa20e2183b3ac373cb65985caa1"

      define_method(:install) do
        bin.install "glab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.12/glab_0.12_darwin_arm64.tar.gz"
      sha256 "fa14652d7ae75db844ff936281ffd8ff7d4f5cbaa956745796fd9d1d79ac7e31"

      define_method(:install) do
        bin.install "glab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.12/glab_0.12_linux_amd64.tar.gz"
      sha256 "e8a52827e6c38f6fcbfc3ce64deae560596321ff52b2fe8ebab82b32c40ebb99"
      define_method(:install) do
        bin.install "glab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.12/glab_0.12_linux_arm64.tar.gz"
      sha256 "ba4305a078da50c6e8a25cf3472a406dfa282281e6e3e7af06aac237b52c266e"
      define_method(:install) do
        bin.install "glab"
      end
    end
  end

  test do
    assert_match "glab version", shell_output("#{bin}/glab --version")
  end
end
