# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glab < Formula
  desc "A CLI tool for GitLab, similar to GitHub CLI (gh)"
  homepage "https://philipkram.github.io/Gitlab-CLI/"
  version "0.3.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.3.0/glab_0.3.0_darwin_amd64.tar.gz"
      sha256 "738ab006ce1759644d7cd5804fa9894247dc6d4dacab544d4773508d319bb5cd"

      define_method(:install) do
        bin.install "glab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.3.0/glab_0.3.0_darwin_arm64.tar.gz"
      sha256 "26f7a4f94a46c1c92d90f1bf2dd7db9cccebbab79ed613f1f7166360c7a4746c"

      define_method(:install) do
        bin.install "glab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.3.0/glab_0.3.0_linux_amd64.tar.gz"
      sha256 "d078538c52c01c9db77e25151121bfd6c117fee46d6bc79990cbbeac8fb1e08b"
      define_method(:install) do
        bin.install "glab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Gitlab-CLI/releases/download/v0.3.0/glab_0.3.0_linux_arm64.tar.gz"
      sha256 "c5d51fba7dd08d5e178bd75235d4f661c17a0142290501931582048c57109ed0"
      define_method(:install) do
        bin.install "glab"
      end
    end
  end

  test do
    assert_match "glab version", shell_output("#{bin}/glab --version")
  end
end
