# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JenkinsCli < Formula
  desc "A CLI tool for controlling Jenkins from the terminal"
  homepage "https://github.com/PhilipKram/Jenkins-CLI"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PhilipKram/Jenkins-CLI/releases/download/v0.1.0/jenkins-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "26abeb5975d720781326dcb60a64a42c460d4d81185eadc82e70653d1986eb44"

      define_method(:install) do
        bin.install "jenkins-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PhilipKram/Jenkins-CLI/releases/download/v0.1.0/jenkins-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "1f1134615232f6fdf309fda772bfa7a478194c8743d6df79a75bec5046b854d0"

      define_method(:install) do
        bin.install "jenkins-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Jenkins-CLI/releases/download/v0.1.0/jenkins-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "cef20b6db522b7428c45a0787ff9db0521523175ab474513700edaee2a56a81c"
      define_method(:install) do
        bin.install "jenkins-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Jenkins-CLI/releases/download/v0.1.0/jenkins-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "baa7392dbee9b8f143daeb62e669241aae77edba56b650b85d4f89ab9a90bb08"
      define_method(:install) do
        bin.install "jenkins-cli"
      end
    end
  end

  test do
    assert_match "jenkins-cli version", shell_output("#{bin}/jenkins-cli --version")
  end
end
