# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JenkinsCli < Formula
  desc "A CLI tool for controlling Jenkins from the terminal"
  homepage "https://github.com/PhilipKram/Jenkins-CLI"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PhilipKram/Jenkins-CLI/releases/download/v0.5.1/jenkins-cli_0.5.1_darwin_amd64.tar.gz"
      sha256 "a71effe1a3b05e5bc17636c040ba0e1abbc88f9129bad272ffceab2d27c17b69"

      define_method(:install) do
        bin.install "jenkins-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PhilipKram/Jenkins-CLI/releases/download/v0.5.1/jenkins-cli_0.5.1_darwin_arm64.tar.gz"
      sha256 "f3d8fd61b76412fe33ce6eb49181551e4070c26732a7dc2a718f4afaaebcfccf"

      define_method(:install) do
        bin.install "jenkins-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Jenkins-CLI/releases/download/v0.5.1/jenkins-cli_0.5.1_linux_amd64.tar.gz"
      sha256 "9354f089ba6dc07dab66318a1f6e49cfa8c7dc33cf719290b4f5378dbf1ebff8"
      define_method(:install) do
        bin.install "jenkins-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PhilipKram/Jenkins-CLI/releases/download/v0.5.1/jenkins-cli_0.5.1_linux_arm64.tar.gz"
      sha256 "978b4c25d93a1205d6170ea282ab3bc6f9b21f54a15467400cd618ece5b46b1a"
      define_method(:install) do
        bin.install "jenkins-cli"
      end
    end
  end

  test do
    system "#{bin}/jenkins-cli", "--version"
  end
end
